# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evdata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'evdata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vdata.proto\x12\x06\x65vdata\"\x07\n\x05\x45mpty\"\x1f\n\rRegionRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"\x9e\x01\n\x06Record\x12\x0e\n\x06region\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x11\n\tparameter\x18\x03 \x01(\t\x12\x0c\n\x04mode\x18\x04 \x01(\t\x12\x12\n\npowertrain\x18\x05 \x01(\t\x12\x0c\n\x04year\x18\x06 \x01(\t\x12\x0c\n\x04unit\x18\x07 \x01(\t\x12\r\n\x05value\x18\x08 \x01(\t\x12\x12\n\npercentage\x18\t \x01(\t\"\x1d\n\nRegionList\x12\x0f\n\x07regions\x18\x01 \x03(\t\"-\n\nRecordList\x12\x1f\n\x07records\x18\x01 \x03(\x0b\x32\x0e.evdata.Record2t\n\x06\x45VData\x12\x30\n\x0bListRegions\x12\r.evdata.Empty\x1a\x12.evdata.RegionList\x12\x38\n\x0bGetByRegion\x12\x15.evdata.RegionRequest\x1a\x12.evdata.RecordListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evdata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_REGIONREQUEST']._serialized_start=33
  _globals['_REGIONREQUEST']._serialized_end=64
  _globals['_RECORD']._serialized_start=67
  _globals['_RECORD']._serialized_end=225
  _globals['_REGIONLIST']._serialized_start=227
  _globals['_REGIONLIST']._serialized_end=256
  _globals['_RECORDLIST']._serialized_start=258
  _globals['_RECORDLIST']._serialized_end=303
  _globals['_EVDATA']._serialized_start=305
  _globals['_EVDATA']._serialized_end=421
# @@protoc_insertion_point(module_scope)
