syntax = "proto3";

package evdata;

service EVData {
  rpc ListRegions(Empty) returns (RegionList);
  rpc GetByRegion(RegionRequest) returns (RecordList);
}

message Empty {}

message RegionRequest {
  string region = 1;
}

message Record {
  string region = 1;
  string category = 2;
  string parameter = 3;
  string mode = 4;
  string powertrain = 5;
  string year = 6;
  string unit = 7;
  string value = 8;
  string percentage = 9;
}

message RegionList {
  repeated string regions = 1;
}

message RecordList {
  repeated Record records = 1;
}
