services:

  xmlrpc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: xmlrpc_service
    working_dir: /app
    command: python xmlrpc/xmlrpc_server.py
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db

  grpc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: grpc_service
    working_dir: /app
    command: python grpc/grpc_server.py
    ports:
      - "50051:50051"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evdb
    ports:
      - "5434:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
